### ISSUE TITLE
Please add Amber support

### ISSUE THREAD

**Issue by timvak** [0xchat-app/0xchat-app-main#1]
Hey team.

I was wondering if you could add support for amber?
https://github.com/greenart7c3/Amber

It's a great way to keep your nsec private.

Thanks for the great work!

**Comment by water783** [comment]
> Hey team.
> 
> I was wondering if you could add support for amber? https://github.com/greenart7c3/Amber
> 
> It's a great way to keep your nsec private.
> 
> Thanks for the great work!

We are using Flutter for development, so integration might be a bit challenging. However, I will add it to our plan.

**Comment by timvak** [comment]
Thank you, no rush :)

**Comment by water783** [comment]
> Thank you, no rush :)

Done!

https://github.com/0xchat-app/0xchat-app-main/releases/tag/v1.2.3-beta
