### ISSUE TITLE
Not building

### ISSUE THREAD

**Issue by frostycodez** [0xchat-app/0xchat-app-main#2]
Trying to setup environment on 3.13.7 but ox_common is using extended_image 8.2.1 which requires Flutter SDK version >=3.16.0 -- what's current flutter version at HEAD? Sorry new to flutter so still getting up to speed on basic dependency system...

**Comment by frostycodez** [comment]
I've tried edge, beta, and now flutter stable and have figured out most of the dependency conflicts but I'm still getting the error below. Can someone share their current pubspec.lock files? Thx.

**Environment**

Flutter 3.22.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 761747bfc5 (4 weeks ago) • 2024-06-05 22:15:13 +0200
Engine • revision edd8546116
Tools • Dart 3.4.3 • DevTools 2.34.3

**Build dependency error**

Because every version of flutter_link_previewer from path depends on flutter_linkify ^6.0.0 which depends on linkify ^5.0.0, every version of flutter_link_previewer from path requires linkify ^5.0.0.
And because every version of flutter_link_previewer from path depends on linkify ^4.1.0, flutter_link_previewer from path is forbidden.
So, because ox_chat depends on ox_chat_ui from path which depends on flutter_link_previewer from path, version solving failed.

**Comment by water783** [comment]
i just updated README.MD, right now we require Flutter 3.19.6
