### ISSUE TITLE
Infinite Loop with Amber?

### ISSUE THREAD

**Issue by Quin5** [0xchat-app/0xchat-app-main#3]
I installed 0xchat using Obtainium.  Upon launch, I chose to sign in with Amber.  I opted for Amber to approve most requests, then got slammed with permission requests from Amber that never seem to end.

**Comment by water783** [comment]
hey, do you still have this issue in the latest version?

**Comment by Quin5** [comment]
I believe that last I saw of it was version 1.3.2.  I'm able to open 0xchat now.  Thank you!
