### ISSUE TITLE
Can't use amber to login

### ISSUE THREAD

**Issue by kehiy** [0xchat-app/0xchat-app-main#4]
Hi, I'm using the latest version with multi account management, but when I try to login using amber, it just close the section.

**Comment by water783** [comment]
First, switch the account in Amber, then click to switch the account in 0xChat?

**Comment by kehiy** [comment]
Worked!

But I think we have to let user to switch in Amber. Otherwise at least show a message like:
Switch your account in Amber.

**Comment by water783** [comment]
Makes sense :)

**Comment by kehiy** [comment]
Yep, If we have this in next version, multi account management will be amazing. also for UI of this multi account thing check telegram. it's very easy to access and known for everyone.

**Comment by kehiy** [comment]
this is fixed in this version i think.
